//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekz.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meropriyatie
    {
        public int MeropriyatieId { get; set; }
        public string Name { get; set; }
        public int GenderId { get; set; }
        public System.DateTime Date { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Country { get; set; }
        public byte[] image { get; set; }
        public string Password { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
