//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekz.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ychastnik
    {
        public int ychastnikId { get; set; }
        public byte[] image { get; set; }
        public string FIO { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    }
}
